### ISSUE TITLE
develop 브랜치에 병합할 게임 수정/추가 필요

### ISSUE THREAD

**Issue by Jinmiru** [Jinmiru/opensource-sw-final-project#30]
게임(2048, 스도쿠 등)이 develop 브랜치에 부족해서...

다른 브랜치에 구현한 기능들(시작 화면 등)과 병합 후 테스트해봐야 할 것 같습니다.

<img width="644" alt="develop 브랜치 병합을 위한 테스트 게임 필요" src="https://github.com/user-attachments/assets/9a41e677-e5e0-4488-8f97-1386d9977b75">

**Comment by JooSungEom** [comment]
이제 슬슬 스도쿠, 스네이크 등등이 마무리 단계라 합치고 닫으면 될 것 같아요.

**Comment by Jinmiru** [comment]
충분히 게임을 합친 것 같으니 닫겠습니다.
