### ISSUE TITLE
develop 브랜치에 병합할 2048게임을 정해야 합니다.

### ISSUE THREAD

**Issue by Jinmiru** [Jinmiru/opensource-sw-final-project#9]
각자 만든 코드 분석 후 적절히 합쳐서 develop 브랜치에 병합해야 할 것 같습니다.

**Comment by pgw2001** [comment]
제 걸로 하시죠

**Comment by Jinmiru** [comment]
확인했습니다.

**Comment by JooSungEom** [comment]
제가 구현한걸 바탕으로 건웅님이 보충과 수정을 해주신거라, develop 브랜츠 병합은 웬만하면 건웅님걸로 진행하면 될 것 같아요.
